### PR TITLE
Request counter + Misc. fixes

### LINKED ISSUE #4: Implement totalRequestsCount
The name is subject to modifications.  
That would be incremented each time an API request is done. That could be useful for some devs to optimize their API request calls or monitoring them over the time.

I'm not sure how to do it, nor how you would like it to be "fetched" by the user. I hope that could be done before you release 0.5.0 though :stuck_out_tongue:

### PR DESCRIPTION
**Pull request by ThePooN**
Implemented request counter, and fixed all tests.
Closes #4

### CODE REVIEW

File: lib/api.js [hunk 1]
```diff
@@ -54,8 +55,12 @@ OsuApi.prototype.getMatch = function(object, id, cb) {
   return require('./api/multiplayer/get_match.js')(this, object, id, cb);
 };
 
-OsuApi.prototype.getScores = function(beatmap_obj, user_obj, mode, cb) {
+OsuApi.prototype.getReplays = function(beatmap_obj, user_obj, mode, cb) {
   return require('./api/user/get_replay.js')(this, beatmap_obj, user_obj, mode, cb);
 };
 
+OsuApi.prototype.getRequestsCount = function() {
```
Comment (nicholastay) [inline lib/api.js]: There's already a property for this in the class instance, why would we need a getter here?

Comment (ThePooN) [inline lib/api.js]: I thought it was more intuitive to get a value by a getter. But that's right, I removed it.
